# Site settings

# REQUIRED CHANGES
# Edit next line, providing your own name.
title: Thao Nguyen | AI Resident
# Edit next line, replacing 'techfolios' with your github username
url: "https://thaoshibe.github.io"
# Edit next line so that baseurl is "" if your repo is <username>.github.io
baseurl: ""
# Specify the rouge syntax highlighter theme. Pick one from css/rouge.

bio-page-label: Resume
# You might want to change the theme associated with one or more sections of the site.
# Defining your own custom theme variations is easy. See the documentation.
theme-home: my-home.html
theme-projects: theme-projects-builtin-1-pj.html
theme-essays: theme-essays-builtin-1-pj.html
theme-bio: my-bio-theme.html
# theme-bio: theme-bio-builtin-2.html
rouge-theme: igopro
# YOU NORMALLY NEVER CHANGE THE FOLLOWING
markdown: kramdown
include: [_data]

